# Practical_6: Numpy

In [2]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [4]:
# Exercise 1
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [6]:
# Exercise 2
a=np.array([[1,2,6],[2,4,5],[5,9,8]])
print(a)

[[1 2 6]
 [2 4 5]
 [5 9 8]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [8]:
# Exercise 3
n=10
m=5
array_num=np.linspace(0,m,n)
array_num = np.interp(
    np.linspace(0, n- 1, n),
    np.arange(len(array_num)),
    array_num
).astype(int)
print(array_num)

[0 0 1 1 2 2 3 3 4 5]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [12]:
matrix_5=np.eye(5)
print(matrix_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [14]:
# Exercise 5
matrix_4=np.eye(4)
print(matrix_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [16]:
# Exercise 6
a=np.array([[9,6,3,4],[4,5,7,6]])
print(a.shape)

(2, 4)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [18]:
# Exercise 7
x=np.arange(16)
matrix=x.reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [20]:
# Exercise 8
x=np.array([1,2,4,5,6,7])
print(type(x))

<class 'numpy.ndarray'>



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [22]:
# Exercise 9
x=np.arange(1,101)
even_numbers=x[x %2==0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [24]:
# Exercise 10
matrix=np.random.randint(10,51,size=(6,6))
print(matrix)


[[23 31 26 16 13 46]
 [10 31 12 29 37 16]
 [28 46 11 43 12 16]
 [39 21 50 26 30 27]
 [19 43 15 47 17 44]
 [50 44 28 24 17 36]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [26]:
# Exercise 11
matrix = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
sub_matrix=matrix[1:4,1:4]
sub_matrix

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [28]:
# Exercise 12
x=np.array([[1,2],[3,4]])
y=np.array([[2,3],[4,5]])
print(np.add(x,y))

[[3 5]
 [7 9]]



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [30]:
# Exercise 13
x=np.array([1,3,4,6,6,7,8,9])
x_mean=np.mean(x)
print('mean_is=',x_mean)
print('==============')

x_median=np.median(x)
print('median_is=',x_median)
print('==============')

x_standard=np.std(x)
print('standard deviation_is=',x_standard)
print('==============')

mean_is= 5.5
median_is= 6.0
standard deviation_is= 2.5



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [32]:
# Exercise 14
x=np.array([1,3,4,6,6,7,8,9])
x_max=np.max(x)
x_min=np.min(x)
print(x_max)
print(x_min)

9
1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [34]:
# Exercise 15
x=np.random.randint(1,50,size=20)
max_x=np.argmax(x)
print(x)
print(len(x))
print(x[max_x])
print(max_x)


[11 11 15 40 31 23  9 38 27  8  9 26 33 28 34 40  8 12 31 45]
20
45
19



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [10]:
# Exercise 16
x=np.array([1,3,4,6,6,7,8,9])
reverse=x[::-1]
print(reverse)

[9 8 7 6 6 4 3 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [12]:
# Exercise 17
n=np.array([[1,2,3],[2,8,9],[2,3,4]])
m=np.array([[2,4,5],[2,4,5],[3,2,1]])
print(np.dot(n,m))

[[15 18 18]
 [47 58 59]
 [22 28 29]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [16]:
# Exercise 18
x=np.array([10,20,30,40])
x_diagonal=np.diag(x)
print(x_diagonal)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [42]:
# Exercise 19
x=np.array([[1,2],[3,4]])
y=np.array([[3,5],[6,7]])
solution=np.dot(x,y)
print('x matrix:\n',x)
print('y matrix:\n',y)
print('solution matrix:\n',solution)

x matrix:
 [[1 2]
 [3 4]]
y matrix:
 [[3 5]
 [6 7]]
solution matrix:
 [[15 19]
 [33 43]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [44]:
# Exercise 20
x=np.array([[1,2,3],[4,5,6]])
y=x.flatten()
print('2D IS:\n',x)
print('1D IS:\n',y)

2D IS:
 [[1 2 3]
 [4 5 6]]
1D IS:
 [1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [46]:
# Exercise 21
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

stack_vertical=np.vstack((x,y))
print('x :\n',x)
print('y :\n',y)
print('Vertical stack:\n',stack_vertical)

x :
 [[1 2]
 [3 4]]
y :
 [[5 6]
 [7 8]]
Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [48]:
# Exercise 22
# Exercise 21
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

stack_horzontal=np.hstack((x,y))
print('x :\n',x)
print('y :\n',y)
print('Horzontal stack:\n',stack_horzontal)

x :
 [[1 2]
 [3 4]]
y :
 [[5 6]
 [7 8]]
Horzontal stack:
 [[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [50]:
# Exercise 23
x=np.array([1,3,4,6,7,8])
x_split=np.split(x,3)
print(x_split)

[array([1, 3]), array([4, 6]), array([7, 8])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [52]:
# Exercise 24
x=np.random.rand(3,3)
x_round=np.round(x,2)
print(x)
print("======================\n")
print(x_round)

[[0.16761023 0.21186224 0.73905849]
 [0.88478605 0.53383529 0.38514676]
 [0.36413943 0.32670004 0.24083744]]

[[0.17 0.21 0.74]
 [0.88 0.53 0.39]
 [0.36 0.33 0.24]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [54]:
# Exercise 25
x=np.array([1,1,2,2,3,4,5,6,7,8,3,4])
x_unique=np.unique(x)
print(x_unique)

[1 2 3 4 5 6 7 8]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [56]:
# Exercise 26
x=np.array([1,2,3,4,5,6,7,8])
x[x <4]=4
print(x)

[4 4 4 4 5 6 7 8]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [58]:
# Exercise 27
x=np.array([1,2,3,4,5])
cumulative_sum_x=np.cumsum(x)
print('X is:\n',x)
print('Cumulative sum:\n',cumulative_sum_x)

X is:
 [1 2 3 4 5]
Cumulative sum:
 [ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [60]:
# Exercise 28
x=np.array([0,10,2,0,3,0,4])
non_xero_x=np.count_nonzero(x)
print(x)
print(non_xero_x)

[ 0 10  2  0  3  0  4]
4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [62]:
# Exercise 29
x=np.random.randint(1,20,size=10)
Ascending_x=np.sort(x)
print(x)
print(Ascending_x)

[16 15 18  8 15  2 13  5  8 13]
[ 2  5  8  8 13 13 15 15 16 18]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [64]:
# Exercise 30
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
row_wise=np.sum(x,axis=1)
column_wise=np.sum(x,axis=0)
print('X is:\n',x)
print('Row wise:\n',row_wise)
print('Column wise:\n',column_wise)

X is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row wise:
 [ 6 15 24]
Column wise:
 [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [66]:
# Exercise 31
x=np.random.randint(10,100,size=(3,4))
x_min=x.min()
x_max=x.max()
normalize_x=(x - x_min)/(x_max - x_min)
print("x is:\n",x)
print("=================================")
print("normarlize for x is:\n",normalize_x)

x is:
 [[67 18 79 61]
 [22 52 98 98]
 [61 58 66 49]]
normarlize for x is:
 [[0.6125 0.     0.7625 0.5375]
 [0.05   0.425  1.     1.    ]
 [0.5375 0.5    0.6    0.3875]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [68]:
# Exercise 32
# Create two NumPy arrays
x = np.array([1, 2, 3])
y= np.array([4, 5, 6])

# Find the dot product
dot_product = np.dot(x, y)

print("Dot Product:", dot_product)

Dot Product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [70]:
# Exercise 33
import numpy as np


x = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


trace_value = np.trace(x)

print("Trace of the matrix:", trace_value)


Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [72]:
# Exercise 34
# Create a 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

print("Original array:")
print(array_2d)


array_2d[[0, 2]] = array_2d[[2, 0]]

print("\nArray after swapping row 0 and row 2:")
print(array_2d)

Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Array after swapping row 0 and row 2:
[[70 80 90]
 [40 50 60]
 [10 20 30]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [74]:
# Exercise 35
# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to a column vector
column_vector = array_1d.reshape(-1, 1)

print("Column vector:")
print(column_vector)

Column vector:
[[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [76]:
# Exercise 36
# Define a 3x3 matrix
matrix = np.array([[2, 5, 3],
                   [1, -2, -1],
                   [1, 3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Determinant:", determinant)

Determinant: -20.000000000000007



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [78]:
# Exercise 37
# Define a 2x2 matrix
matrix = np.array([[4, 2],
                   [1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [80]:
# Exercise 38

# Coefficient matrix A
A = np.array([[2, 3],
              [3, 4]])

# Constant terms vector B
B = np.array([8, 11])

# Solve the system
solution = np.linalg.solve(A, B)

print("Solution [x, y]:", solution)

Solution [x, y]: [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [82]:
# Exercise 39
# Create an original NumPy array
original_array = np.array([10, 20, 30, 40, 50])

# Define noise parameters
mean = 0        # Mean of the noise
std_dev = 2     # Standard deviation of the noise

# Generate Gaussian noise
noise = np.random.normal(mean, std_dev, original_array.shape)

# Add noise to the original array
noisy_array = original_array + noise

print("Original array:", original_array)
print("Noise:", noise)
print("Noisy array:", noisy_array)

Original array: [10 20 30 40 50]
Noise: [-0.69799462  0.97010753 -0.43226734 -2.23969932  2.4869793 ]
Noisy array: [ 9.30200538 20.97010753 29.56773266 37.76030068 52.4869793 ]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [84]:
# Exercise 40
# Create a 4x4 matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Extract the diagonal elements
diagonal_elements = np.diag(matrix)

print("Original matrix:")
print(matrix)

print("\nDiagonal elements:")
print(diagonal_elements)


Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements:
[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [86]:
# Exercise 41
start=10
stop=50
size=100
x=np.random.randint(start,stop,size)
print(x)
print(len(x))

[31 46 25 11 23 48 42 49 46 26 44 31 16 43 37 20 32 38 22 42 47 48 19 21
 30 18 10 28 37 33 22 22 46 49 47 13 28 39 14 26 30 34 24 11 33 23 14 45
 43 24 23 36 32 19 24 28 46 42 28 40 49 10 25 29 14 24 29 47 38 32 34 44
 47 47 35 39 37 17 45 38 12 25 34 40 31 32 19 38 27 27 41 15 25 34 47 18
 41 15 11 25]
100



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [88]:
# Exercise 42
x=np.array([[5,-3,2],[-1,7,-6]])
x[x <0]= 0
print(x)

[[5 0 2]
 [0 7 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [90]:
# Exercise 43
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product=np.inner(a,b)
outer_product=np.outer(a,b)

print("Inner product:", inner_product)
print("\nOuter product:\n", outer_product)

Inner product: 32

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [92]:
# Exercise 44
from scipy.spatial import distance_matrix
points = np.array([[0, 0],
                   [1, 1],
                   [2, 0]])
dist_matrix = distance_matrix(points, points)

print("Pairwise distance matrix:")
print(dist_matrix)

Pairwise distance matrix:
[[0.         1.41421356 2.        ]
 [1.41421356 0.         1.41421356]
 [2.         1.41421356 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [94]:
# Exercise 45
person_dtype = np.dtype([('name', 'U20'), 
                         ('age', 'i4'),    
                         ('height', 'f4')]) 

people = np.array([('Alice', 25, 5.5),
                   ('Bob', 30, 6.0),
                   ('Charlie', 22, 5.8)], dtype=person_dtype)

print(people)

[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [96]:
# Exercise 46
matrix = np.random.randint(0, 10, size=(5, 5))

print("Matrix:")
print(matrix)

unique_values, counts = np.unique(matrix, return_counts=True)

for val, count in zip(unique_values, counts):
    print(f"Value {val} occurs {count} times")

Matrix:
[[2 7 2 1 6]
 [0 7 4 7 5]
 [4 5 4 3 3]
 [8 3 2 1 8]
 [2 6 4 9 6]]
Value 0 occurs 1 times
Value 1 occurs 2 times
Value 2 occurs 4 times
Value 3 occurs 3 times
Value 4 occurs 4 times
Value 5 occurs 2 times
Value 6 occurs 3 times
Value 7 occurs 3 times
Value 8 occurs 2 times
Value 9 occurs 1 times



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [98]:
# Exercise 47
arr = np.random.rand(3, 3)
row_means = arr.mean(axis=1, keepdims=True)
result = arr - row_means
print('Array is:\n',arr)
print("=================")
print("Mean is\n",row_means)
print("=================")
print("Result is:\n",result)

Array is:
 [[0.97001154 0.02211098 0.09096061]
 [0.82509323 0.95355716 0.41623109]
 [0.30178587 0.4446554  0.57234822]]
Mean is
 [[0.36102771]
 [0.73162716]
 [0.4395965 ]]
Result is:
 [[ 0.60898383 -0.33891673 -0.2700671 ]
 [ 0.09346607  0.22193    -0.31539607]
 [-0.13781062  0.0050589   0.13275172]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [100]:
# Exercise 48
arr = np.random.randint(0, 100, size=10)
any_greater_than_50 = np.any(arr > 50)

print(arr)
print("Any values greater than 50:", any_greater_than_50)

[78 32 51 36  6 97 49 91 81 24]
Any values greater than 50: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [102]:
# Exercise 49
def moving_average(arr, window_size):
    return np.convolve(arr, np.ones(window_size)/window_size, mode='valid')

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
ma = moving_average(arr, window_size)

print(ma)

[2. 3. 4. 5. 6. 7. 8.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [104]:
# Exercise 50
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

correlation = np.corrcoef(x, y)[0, 1]


print("Pearson correlation coefficient:", correlation)

Pearson correlation coefficient: -0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [106]:
# Exercise 51
radians = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
degrees = np.degrees(radians)

print(degrees)

[  0.  90. 180. 270. 360.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [108]:
# Exercise 52
arr = np.random.rand(10)
variance = np.var(arr)
std_dev = np.std(arr)

print("Array:", arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Array: [0.07186792 0.43037375 0.01114936 0.4480784  0.0614717  0.73505383
 0.23663211 0.32715583 0.42358769 0.35156286]
Variance: 0.044231701368651385
Standard Deviation: 0.21031334091933251



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [110]:
# Exercise 53
arr = np.random.rand(4, 5)
max_indices_axis0 = np.argmax(arr, axis=0)
max_indices_axis1 = np.argmax(arr, axis=1)

print("Array:\n", arr)
print("Indices of max values along axis 0:", max_indices_axis0)
print("Indices of max values along axis 1:", max_indices_axis1)

Array:
 [[0.58731856 0.25653934 0.96704539 0.14076076 0.5587311 ]
 [0.43445491 0.88237406 0.00333579 0.06275934 0.83030365]
 [0.11601366 0.11223597 0.42816853 0.20482227 0.22833782]
 [0.06788128 0.98736289 0.63069237 0.61357083 0.69872373]]
Indices of max values along axis 0: [0 3 0 3 1]
Indices of max values along axis 1: [2 1 2 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [112]:
# Exercise 54
matrix = np.array([[4, 7],
                   [2, 6]])

inverse = np.linalg.inv(matrix)

print("Inverse matrix:")
print(inverse)

Inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [114]:
# Exercise 55
arr = np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)

print("Original array:", arr)
print("Standardized array:", standardized)

Original array: [0.93041939 0.40473628 0.75578757 0.20530455 0.06379914 0.94645523
 0.93211309 0.77702274 0.81480113 0.86734077]
Standardized array: [ 0.84766079 -0.86197151  0.27972128 -1.51056553 -1.97077095  0.8998127
  0.85316904  0.34878255  0.47164582  0.64251582]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [116]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b

print("Addition:", addition)
print("Subtraction:", subtraction)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [118]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of maximum element:", max_index)

Array: [0.49119605 0.01193675 0.71481856 0.71081121 0.21428402 0.54149661
 0.9760695  0.32759892 0.48361486 0.61954409]
Index of maximum element: 6



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [120]:
# Exercise 58
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

rotated = np.rot90(arr)

print(rotated)

[[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [122]:
# Exercise 59
matrix = np.array([[1, 2],
                   [3, 4]])

frobenius_norm = np.linalg.norm(matrix, 'fro')

print("Frobenius norm:", frobenius_norm)

Frobenius norm: 5.477225575051661



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [124]:
# Exercise 60
arr = np.arange(27).reshape((3, 3, 3))

subarray = arr[1:, :2, 1:]

print("Original array:\n", arr)
print("\nSliced subarray:\n", subarray)








Original array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Sliced subarray:
 [[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]



---